control_points:
   - apf_cp_upper_arm_link_0
   - apf_cp_upper_arm_link_1
   - apf_cp_forearm_link_0
   - apf_cp_forearm_link_1
   - apf_cp_forearm_link_2
   - apf_cp_forearm_link_3
   - apf_cp_wrist_1_link
   - apf_cp_wrist_2_link
   - apf_cp_wrist_3_link
   - apf_cp_tool_center_point
ro: 0.4 # Search radius
depth_image_topic: "/camera1/depth_registered_filtered/image_rect" # "/camera1/depth_registered_filtered/image_rect"   /camera1/depth_obstacles/image
camera_info_topic: "/camera1/depth_registered_filtered/camera_info" # "/camera1/depth_registered_filtered/camera_info"
fixed_frame: "base_link"
legacy_dist_calc: False
loose_timing: True
do_post_processing: True
post_processing:
   bg_threshold: 4.25 # 3.0
   canny_threshold: [20, 200]
   close_k_size: 60
   dilate_k_size: 50
   frame_buffer_size: 3
   median_filter_k_size: 5
   min_contour_area: 4000
   replace_value: 0.0
   gui: True
