#
#  REUSED CONFIG
#

# Settings for ros_control control loop
hardware_control_loop:
   loop_hz: &loop_hz 500
   loop_T: &loop_T 0.002

# Settings for ros_control hardware interface
ur_hardware_interface:
   joints: &robot_joints
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint

apf_collision_avoidance:
   cps: &cps
      - apf_cp_upper_arm_link_0
      - apf_cp_upper_arm_link_1
      - apf_cp_forearm_link_0
      - apf_cp_forearm_link_1
      - apf_cp_forearm_link_2
      - apf_cp_forearm_link_3
      - apf_cp_wrist_1_link
      - apf_cp_wrist_2_link
      - apf_cp_wrist_3_link
      - apf_cp_tool_center_point

apf_collision_avoidance:
   constraints: &constraints
      goal_time: 0.6
      stopped_velocity_tolerance: 0.08
      shoulder_pan_joint: {trajectory: 0.5, goal: 0.1}
      shoulder_lift_joint: {trajectory: 0.5, goal: 0.1}
      elbow_joint: {trajectory: 0.5, goal: 0.1}
      wrist_1_joint: {trajectory: 0.8, goal: 0.1}
      wrist_2_joint: {trajectory: 0.8, goal: 0.1}
      wrist_3_joint: {trajectory: 0.8, goal: 0.1}

apf_collision_avoidance:
   flacco_params: &flacco_params
      v_max: 2
      alpha: 6
      vd_max: 0.5
      c: 5
      ro: 0.70
      pivot_rep_vector: True
   robot_structure: &robot_structure
      cp_names: *cps
      base_segment: "base_link"
      ee_segment: "apf_cp_wrist_3_link"
      joint_limits_ns: "/robot_description_planning"
   camera: &camera_config
      camera_ns: "/camera1/aligned_depth_to_color"
      camera_frame: "rs_d435_cam_depth_optical_frame"
      robot_frame: "base_link"

#
#  CONTROLLERS
#

# Position Flacco APF config
flacco_apf_controller:
   type: position_controllers/FlaccoApfJointTrajectoryController6DOFs
   joints: *robot_joints
   constraints: *constraints
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20
   flacco: *flacco_params
   robot_struct: *robot_structure      
   camera: *camera_config
   control_period: *loop_T

# Velocity Controller
vel_flacco_apf_controller:
   type: velocity_controllers/FlaccoApfJointTrajectoryController6DOFs
   joints: *robot_joints
   constraints: *constraints
   stop_trajectory_duration: 0.5
   state_publish_rate: *loop_hz
   action_monitor_rate: 20
   flacco: *flacco_params
   robot_struct: *robot_structure
   camera: *camera_config
   control_period: *loop_T
   filter_coeff: 0.9965
   gains:
      shoulder_pan_joint:  {p: 2.0,  i: 0, d: 0.1, i_clamp: 1}
      shoulder_lift_joint: {p: 2.0,  i: 0, d: 0.1, i_clamp: 1}
      elbow_joint:         {p: 2.0,  i: 0, d: 0.1, i_clamp: 1}
      wrist_1_joint:       {p: 2.0,  i: 0, d: 0.1, i_clamp: 1}
      wrist_2_joint:       {p: 2.0,  i: 0, d: 0.1, i_clamp: 1}
      wrist_3_joint:       {p: 2.0,  i: 0, d: 0.1, i_clamp: 1}
   velocity_ff:
      shoulder_pan_joint: 1
      shoulder_lift_joint: 1
      elbow_joint: 1
      wrist_1_joint: 1
      wrist_2_joint: 1
      wrist_3_joint: 1
